services:
  web:
    build:
      context: ../..
      dockerfile: docker/development/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && rails server -b 0.0.0.0"
    develop:
      watch:
        - action: sync
          path: ./app
          target: ./build/app
    volumes:
      - ../..:/build:rw
    ports:
      - "3000:3000"
