language: ruby
rvm:
  - 2.3.0
bundler_args: --without development staging production
sudo: false
before_script:
  - bundle exec rake db:test:prepare
  - echo 'Canada/Pacific' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
