services:
  rails:
    image: ghcr.io/sc0v/binder-devcontainer:latest
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      RAILS_ENV: development
    env_file:
      - .env.local

volumes: {}
