default: &default
  host: ldap.cmu.edu
  port: 636
  method: ssl
  base: dc=andrew,dc=cmu,dc=edu

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
