
Tool.create([
  { name:"Reel Tape Measure", barcode: 1453, description:"300' Black"},
  { name:"Reel Tape Measure", barcode: 1452, description:"300' Yellow"},
  { name:"Reel Tape Measure", barcode: 1454, description:"200' Orange"},
  { name:"Tape Gun", barcode: 1451, description:"Red"},
  { name:"Tape Measure", barcode: 1450, description:"25' Workforce - Yellow"},
  { name:"Drill", barcode: 1241, description:"DeWalt 9.6v"},
  { name:"Battery", barcode: 1384, description:"DeWalt 9.6v"},
  { name:"Tape Measure", barcode: 1382, description:"30' Stanley LeverLock (nice)"},
  { name:"Power Strip", barcode: 1381, description:"6 Outlet"},
  { name:"Hot Glue Gun", barcode: 1380, description:"Arrow ElectroMatic"},
  { name:"EH&S Hardhat", barcode: 1470, description:"Neon Yellow"},
  { name:"EH&S Hardhat", barcode: 1527, description:"Neon Yellow"},
  { name:"EH&S Hardhat", barcode: 1528, description:"Neon Yellow"},
  { name:"EH&S Hardhat", barcode: 1526, description:"Neon Yellow"},
  { name:"EH&S Hardhat", barcode: 1471, description:"Neon Yellow"},
  { name:"SCC Hardhat", barcode: 1336, description:"Blue"},
  { name:"SCC Hardhat", barcode: 1337, description:"Blue"},
  { name:"SCC Hardhat", barcode: 1343, description:"Blue"},
  { name:"SCC Hardhat", barcode: 1455, description:"Blue"},
  { name:"SCC Hardhat", barcode: 1334, description:"Blue"},
  { name:"SCC Hardhat", barcode: 1344, description:"Blue"},
  { name:"SCC Hardhat", barcode: 1342, description:"Blue"},
  { name:"SCC Hardhat", barcode: 1339, description:"Blue"},
  { name:"SCC Hardhat", barcode: 1338, description:"Blue"},
  { name:"SCC Hardhat", barcode: 1341, description:"Blue"},
  { name:"SCC Hardhat", barcode: 1340, description:"Blue"},
  { name:"SCC Hardhat", barcode: 1345, description:"Blue"},
  { name:"Org Hardhat", barcode: 1353, description:"White"},
  { name:"Org Hardhat", barcode: 1350, description:"White"},
  { name:"Org Hardhat", barcode: 1351, description:"White"},
  { name:"Org Hardhat", barcode: 1348, description:"White"},
  { name:"Org Hardhat", barcode: 1349, description:"White"},
  { name:"Org Hardhat", barcode: 1352, description:"White"},
  { name:"Org Hardhat", barcode: 1347, description:"White"},
  { name:"Org Hardhat", barcode: 1379, description:"White"},
  { name:"SCC Hardhat", barcode: 1378, description:"Blue"},
  { name:"SCC Hardhat", barcode: 1377, description:"Blue"},
  { name:"SCC Hardhat", barcode: 1376, description:"Blue"},
  { name:"SCC Hardhat", barcode: 1375, description:"Blue"},
  { name:"SCC Hardhat", barcode: 1374, description:"Blue"},
  { name:"SCC Hardhat", barcode: 1373, description:"Blue"},
  { name:"SCC Hardhat", barcode: 1372, description:"Blue"},
  { name:"SCC Hardhat", barcode: 1371, description:"Blue"},
  { name:"SCC Hardhat", barcode: 1370, description:"Blue"},
  { name:"SCC Hardhat", barcode: 1369, description:"Blue"},
  { name:"SCC Hardhat", barcode: 1368, description:"Blue"},
  { name:"SCC Hardhat", barcode: 1367, description:"Blue"},
  { name:"SCC Hardhat", barcode: 1366, description:"Blue"},
  { name:"SCC Hardhat", barcode: 1365, description:"Blue"},
  { name:"SCC Hardhat", barcode: 1364, description:"Blue"},
  { name:"SCC Hardhat", barcode: 1363, description:"Blue"},
  { name:"SCC Hardhat", barcode: 1529, description:"Blue"},
  { name:"SCC Hardhat", barcode: 1530, description:"Blue"},
  { name:"SCC Hardhat", barcode: 1531, description:"Blue"},
  { name:"SCC Hardhat", barcode: 1532, description:"Blue"},
  { name:"SCC Hardhat", barcode: 1533, description:"Blue"},
  { name:"SCC Hardhat", barcode: 1534, description:"Blue"},
  { name:"SCC Hardhat", barcode: 1535, description:"Blue"},
  { name:"SCC Hardhat", barcode: 1536, description:"Blue"},
  { name:"SCC Hardhat", barcode: 1537, description:"Blue"},
  { name:"Org Hardhat", barcode: 1545, description:"White"},
  { name:"Org Hardhat", barcode: 1544, description:"White"},
  { name:"Org Hardhat", barcode: 1543, description:"White"},
  { name:"Org Hardhat", barcode: 1542, description:"White"},
  { name:"Org Hardhat", barcode: 1541, description:"White"},
  { name:"Org Hardhat", barcode: 1540, description:"White"},
  { name:"Org Hardhat", barcode: 1539, description:"White"},
  { name:"Org Hardhat", barcode: 1538, description:"White"},
  { name:"Org Hardhat", barcode: 1566, description:"White"},
  { name:"Org Hardhat", barcode: 1567, description:"White"},
  { name:"Broom", barcode: 1549, description:"Push Broom"},
  { name:"Broom", barcode: 1548, description:"Push Broom"},
  { name:"Broom", barcode: 1546, description:"Push Broom"},
  { name:"Broom", barcode: 1547, description:"Push Broom"},
  { name:"Broom", barcode: 1549, description:"Push Broom - Broken Handle"},
  { name:"Dustpan", barcode: 1554, description:""},
  { name:"Dustpan", barcode: 1552, description:""},
  { name:"Dustpan", barcode: 1553, description:""},
  { name:"Level", barcode: 1556, description:"4' Yellow"},
  { name:"Level", barcode: 1557, description:"4' Yellow"},
  { name:"Level", barcode: 1558, description:"4' Yellow"},
  { name:"Level", barcode: 1559, description:"4' Yellow"},
  { name:"Level", barcode: 1560, description:"4' Yellow"},
  { name:"Level", barcode: 1563, description:"4' Metal"},
  { name:"Level", barcode: 1562, description:"4' Metal"},
  { name:"Level", barcode: 1561, description:"4' Metal"},
  { name:"Level", barcode: 1564, description:"2' Yellow"},
  { name:"EH&S Hardhat", barcode: 1568, description:"Neon Yellow"},
  { name:"EH&S Hardhat", barcode: 1569, description:"Neon Yellow"},
  { name:"EH&S Hardhat", barcode: 1570, description:"Neon Yellow"},
  { name:"EH&S Hardhat", barcode: 1571, description:"Neon Yellow"},
  { name:"EH&S Hardhat", barcode: 1572, description:"Neon Yellow"},
  { name:"EH&S Hardhat", barcode: 1573, description:"Neon Yellow"},
  { name:"EH&S Hardhat", barcode: 1574, description:"Neon Yellow"},
  { name:"EH&S Hardhat", barcode: 1575, description:"Neon Yellow"},
  { name:"EH&S Hardhat", barcode: 1576, description:"Neon Yellow"},
  { name:"EH&S Hardhat", barcode: 1578, description:"Neon Yellow"},
  { name:"EH&S Hardhat", barcode: 1577, description:"Neon Yellow"},
  { name:"EH&S Hardhat", barcode: 1579, description:"Neon Yellow"},
  { name:"EH&S Hardhat", barcode: 1580, description:"Neon Yellow"},
  { name:"EH&S Hardhat", barcode: 1581, description:"Neon Yellow"},
  { name:"EH&S Hardhat", barcode: 1582, description:"Neon Yellow"},
  { name:"EH&S Hardhat", barcode: 1583, description:"Neon Yellow"},
  { name:"Circular Saw", barcode: 1584, description:"Milwakee"},
  { name:"Circular Saw", barcode: 1585, description:"Milwakee"},
  { name:"Drill", barcode: 1586, description:"DeWalt 18v"},
  { name:"Battery", barcode: 1587, description:"DeWalt 18v"},
  { name:"Battery", barcode: 1588, description:"DeWalt 18v"},
  { name:"Drill", barcode: 1589, description:"DeWalt 18v XRP"},
  { name:"Battery", barcode: 1590, description:"DeWalt 14v"},
  { name:"Drill", barcode: 1591, description:"DeWalt 18v"},
  { name:"Battery", barcode: 1592, description:"DeWalt 18v"},
  { name:"Battery", barcode: 1594, description:"DeWalt 18v"},
  { name:"Battery", barcode: 1593, description:"DeWalt 18v"},
  { name:"Drill", barcode: 1595, description:"DeWalt 18v"},
  { name:"Drill", barcode: 1596, description:"DeWalt 18v"},
  { name:"Battery", barcode: 1598, description:"DeWalt 18v"},
  { name:"Battery", barcode: 1597, description:"DeWalt 18v"},
  { name:"Drill", barcode: 1601, description:"DeWalt 18v"},
  { name:"Battery", barcode: 1599, description:"DeWalt 18v"},
  { name:"Battery", barcode: 1600, description:"DeWalt 18v"},
  { name:"Drill", barcode: 1602, description:"DeWalt 18v"},
  { name:"Battery", barcode: 1603, description:"DeWalt 18v"},
  { name:"Battery", barcode: 1604, description:"DeWalt 18v"},
  { name:"Paint Sprayer", barcode: 1605, description:"Wagner"},
  { name:"Paint Sprayer", barcode: 1606, description:"Wagner"},
  { name:"Lamp", barcode: 1607, description:"Clip on, Metal shade"},
  { name:"Lamp", barcode: 1608, description:"Clip on, Metal shade"},
  { name:"Lamp", barcode: 1609, description:"Clip on, Metal shade"},
  { name:"Lamp", barcode: 1610, description:"Yellow Trouble Light"},
  { name:"Power Strip", barcode: 1611, description:"6 Outlet"},
  { name:"Power Strip", barcode: 1612, description:"Org/Blk 3-Outlet"},
  { name:"Power Strip", barcode: 1613, description:"Black 6-Outlet"},
  { name:"Extension Cord", barcode: 1614, description:"Black, 6 ft"},
  { name:"Jigsaw", barcode: 1615, description:"Porter-Cable"},
  { name:"Jigsaw", barcode: 1616, description:"Porter-Cable"},
  { name:"Jigsaw", barcode: 1617, description:"Porter-Cable"},
  { name:"Hammer", barcode: 1618, description:"Wooden"},
  { name:"Hammer", barcode: 1619, description:"Yellow/Blk"},
  { name:"Scissors", barcode: 1620, description:"Kitchen-Aid Red Handle"},
  { name:"Chisel", barcode: 1621, description:""},
  { name:"Hammer", barcode: 1622, description:"Yellow/Blk"},
  { name:"Hammer", barcode: 1623, description:"Red/Blk"},
  { name:"Hand Saw", barcode: 1624, description:"Wooden Handle"},
  { name:"Hand Clamp", barcode: 1626, description:"Irwin"},
  { name:"Hand Clamp", barcode: 1625, description:""},
  { name:"Hacksaw", barcode: 1627, description:""},
  { name:"Hand Saw", barcode: 1628, description:""},
  { name:"Circular Saw", barcode: 1629, description:"DeWalt"},
  { name:"Circular Saw", barcode: 1630, description:"DeWalt"},
  { name:"Crowbar", barcode: 1631, description:"Big"},
  { name:"Crowbar", barcode: 1632, description:"Big"},
  { name:"Crowbar", barcode: 1633, description:"Eliza"},
  { name:"Hammer", barcode: 1634, description:"Blk/Yellow"},
  { name:"Maglite", barcode: 1635, description:"Black"},
  { name:"Staple Gun", barcode: 1637, description:""},
  { name:"Staple Gun", barcode: 1636, description:""},
  { name:"Staple Gun", barcode: 1638, description:""},
  { name:"Hand Clamp", barcode: 1639, description:"Irwin"},
  { name:"Hand Clamp", barcode: 1640, description:"Irwin"},
  { name:"Caulk Gun", barcode: 1641, description:"Blue"},
  { name:"Caulk Gun", barcode: 1642, description:"Silver"},
  { name:"Caulk Gun", barcode: 1643, description:"Blue"},
  { name:"Circular Saw", barcode: 1644, description:"Skilsaw"},
  { name:"Sawzall", barcode: 1645, description:"DeWalt"},
  { name:"Jigsaw", barcode: 1646, description:"Black & Decker"},
  { name:"Jigsaw", barcode: 1647, description:"DeWalt"},
  { name:"Miter Saw", barcode: 1550, description:"DeWalt"},
  { name:"Broom", barcode: 1649, description:"Blue Handle - Straw"},
  { name:"Broom", barcode: 1650, description:"Push Broom"},
  { name:"Staple Gun", barcode: 1652, description:""},
  { name:"Staple Gun", barcode: 1651, description:""},
  { name:"Staple Gun", barcode: 1648, description:""},
  { name:"Box of Hole-Saws", barcode: 1653, description:"Check that all are present"},
  { name:"Shopvac", barcode: 1654, description:"Orange"},
  { name:"Shopvac", barcode: 1655, description:"Orange"},
  { name:"Dustpan", barcode: 1656, description:""},
  { name:"Telecom Radio", barcode: 42, description:"Motorola PR400"},
  { name:"SCC Radio", barcode: 2, description:"Motorola CP200"},
  { name:"SCC Radio", barcode: 3, description:"Motorola CP200"},
  { name:"SCC Radio", barcode: 4, description:"Motorola CP200"},
  { name:"SCC Radio", barcode: 5, description:"Motorola CP200"},
  { name:"SCC Radio", barcode: 6, description:"Motorola CP200"},
  { name:"SCC Radio", barcode: 7, description:"Motorola CP200"},
  { name:"SCC Radio", barcode: 8, description:"Motorola CP200"},
  { name:"SCC Radio", barcode: 9, description:"Motorola CP200"},
  { name:"SCC Radio", barcode: 10, description:"Motorola CP200"},
  { name:"SCC Radio", barcode: 11, description:"Motorola CP200"},
  { name:"SCC Radio", barcode: 12, description:"Motorola CP200"},
  { name:"SCC Radio", barcode: 13, description:"Motorola CP200"},
  { name:"SCC Radio", barcode: 14, description:"Motorola CP200"},
  { name:"SCC Radio", barcode: 15, description:"Motorola CP200"},
  { name:"SCC Radio", barcode: 16, description:"Motorola CP200"},
  { name:"SCC Radio", barcode: 17, description:"Motorola CP200"},
  { name:"SCC Radio", barcode: 18, description:"Motorola CP200"},
  { name:"SCC Radio", barcode: 19, description:"Motorola CP200"},
  { name:"SCC Radio", barcode: 20, description:"Motorola CP200"},
  { name:"SCC Radio", barcode: 22, description:"Motorola CP200"},
  { name:"SCC Radio", barcode: 23, description:"Motorola CP200"},
  { name:"SCC Radio", barcode: 24, description:"Motorola CP200"},
  { name:"Watch Shift Radio", barcode: 103, description:"Motorola HT750"},
  { name:"Watch Shift Radio", barcode: 105, description:"Motorola HT750"},
  { name:"Watch Shift Radio", barcode: 104, description:"Motorola HT750"},
  { name:"Watch Shift Radio", barcode: 107, description:"Motorola HT750"},
  { name:"Watch Shift Radio", barcode: 102, description:"Motorola HT750"},
  { name:"Watch Shift Radio", barcode: 106, description:"Motorola HT750"},
  { name:"Watch Shift Radio", barcode: 108, description:"Motorola HT750"},
  { name:"Watch Shift Radio", barcode: 101, description:"Motorola HT750"}])
