name: Auto Timestamp Tag

on:
  push:
    branches:
      - master

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Generate timestamp tag
        id: tag
        run: |
          TIMESTAMP=$(date -u +"v%Y.%m.%d-%H%M")
          echo "tag=$TIMESTAMP" >> $GITHUB_OUTPUT

      - name: Create Git tag
        run: |
          git tag ${{ steps.tag.outputs.tag }}
          git push origin ${{ steps.tag.outputs.tag }}
